export const queries = {
    getAllDenuncias: "select * from DENUNCIAS;",
    getDenunciasWithPublicInfo : "select DENUNCIAS.hechos as hechos, ABUSADOR.nombres+' '+ABUSADOR.apellidoPat+' '+ABUSADOR.apellidoMat as nombreAbusador, DENUNCIAS.TIPOVIOLENCIA as tipoV, MUNICIPIOS.nombre as municipio, ESCUELAS.Nombre as insti, ESCUELAS.NIVELESCUELA as ns from DENUNCIAS inner join ESCUELAS on DENUNCIAS.idEscuela = ESCUELAS.idEscuela inner join MUNICIPIOS on ESCUELAS.idMunicipio = MUNICIPIOS.idMunicipio inner join ABUSADOR on DENUNCIAS.idAbusador = ABUSADOR.idAbusador;",
    getDenunciasBySchool: "select * from DENUNCIAS where idEscuela = @idEscuela",
    registerNewDenuncia: "INSERT INTO DENUNCIAS values (@hechos, @fechaDenuncia, @idDenunciante, @idAbusador, @idEscuela, @ACCIONTOMADA, @SERVICIOADD, @INFOTIPOSVIOLENCIA, @MECANISMOSDENUNCIAS, @TEMPORALIDAD, @ZONA, @NIVELGRAVEDAD, @TIPOVIOLENCIA, @SUCEDIOALGO)",
    deleteDenuncia: "Delete from DENUNCIAS where idDenuncia = @idDenuncia",
    updateDenucnia: "Update Denuncias set hechos = @hechos, fechaDenuncia = @fechaDenuncia, idDenunciante = @idDenunciante, idAbusador = @idAbusador, idEscuela = @idEscuela, ACCIONTOMADA = @ACCIONTOMADA, SERVICIOADD = @SERVICIOADD, INFOTIPOSVIOLENCIA = @INFOTIPOSVIOLENCIA, MECANISMOSDENUNCIAS = @MECANISMOSDENUNCIAS, TEMPORALIDAD = @TEMPORALIDAD, ZONA = @ZONA, NIVELGRAVEDAD = @NIVELGRAVEDAD, TIPOVIOLENCIA = @TIPOVIOLENCIA, SUCEDIOALGO = @SUCEDIOALGO where idDenuncia = @idDenuncia",
    getDenunciaP:"select count(TIPOVIOLENCIA) as cant from DENUNCIAS where TIPOVIOLENCIA='Patrimonial';",
    getDenunciaS:"select count(TIPOVIOLENCIA) as cant from DENUNCIAS where TIPOVIOLENCIA='Sexual';",
    getDenunciaF:"select count(TIPOVIOLENCIA) as cant from DENUNCIAS where TIPOVIOLENCIA='Física';",
    getDenunciaPV:"select count(TIPOVIOLENCIA) as cant from DENUNCIAS where TIPOVIOLENCIA='Psicológica/Verbal';",
    getEscuelas: "select * from ESCUELAS;",
    getEscuelasMS: "select count(NIVELESCUELA) as cant from DENUNCIAS inner join ESCUELAS on DENUNCIAS.idEscuela = ESCUELAS.idEscuela where ESCUELAS.NIVELESCUELA = 'Media S';",
    getEscuelaS: "select count(NIVELESCUELA) as cant from DENUNCIAS inner join ESCUELAS on DENUNCIAS.idEscuela = ESCUELAS.idEscuela where ESCUELAS.NIVELESCUELA = 'Superior';",
    getEscuelasByState: "Select * from ESCUELAS Where idMunicipio = @idMunicipio",
    getEscuelasByLevel: "select * from ESCUELAS where NIVELESCUELA = @NIVELESCUELA",
    getEscuelasByLevelAndState : "Select * from ESCUELAS where idMunicipio = @idMunicipio and NIVELESCUELA = @NIVELESCUELA",
    registerNewDenunciante: "Insert into DENUNCIANTES values (@nombreDenunciante, @contacto, @sexo, @edad, @rol)",
    getDenuncianteEspecifico: "select * from  DENUNCIANTES where nombreDenunciante = @nombreDenunciante and contacto = @contacto and sexo = @sexo and edad = @edad and rol = @rol",
    getDenuncianteH:"select count(sexo) as cant from DENUNCIANTES where sexo='H';",
    getDenuncianteM:"select count(sexo) as cant from DENUNCIANTES where sexo='M';",
    registerAbusador: "Insert into ABUSADOR values (@nombres, @apellidoPat, @apellidoMat, @sexo, @rol)",
    getAbusadorEspecifico: "select * from  ABUSADOR where nombres = @nombres and apellidoPat = @apellidoPat and apellidoMat = @apellidoMat and sexo = @sexo and rol = @rol",
    getAbusadorH: "select count(sexo) as cant from ABUSADOR where sexo='H';",
    getAbusadorM: "select count(sexo) as cant from ABUSADOR where sexo='M';",
    getMunicipios: "select * from MUNICIPIOS",
    getLogin : "select * from ADMINISTRADORES WHERE usuario = @usuario COLLATE SQL_Latin1_General_CP1_CS_AS AND contra = @password COLLATE SQL_Latin1_General_CP1_CS_AS",
    getSuperLogin : "select * from ADMINISTRADORES WHERE usuario = @usuario AND contra = @contra"
}